services:
  fitness-web:
    build:
      context: .
      args:
        - APP_URL=${APP_URL}
        - APP_PORT=${APP_PORT}
        - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
    container_name: fitness-web
    restart: unless-stopped
    networks:
      - caddy_network
    labels:
      caddy: ${APP_URL}
      caddy.handle: /*
      caddy.handle.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy_network:
    external: true